### ISSUE TITLE
Doesn't work with bucket names that contain dots

### ISSUE THREAD

**Issue by mconigliaro** [MayaraCloud/apt-transport-s3#32]
```
Err:7 s3://packages.example.com.s3.amazonaws.com/ubuntu xenial-unstable/main amd64 Packages
  CertificateError: hostname 'packages.example.com.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'
```

**Comment by rasathus** [comment]
The AWS Docs make some suggestions around this ...  

> When using virtual hosted–style buckets with SSL, the SSL wildcard certificate only matches buckets that do not contain periods. - https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

By using dots in your bucket names you're invalidating the TLS certificate provided to the client.  In most cases you would be better served by avoiding the use of dots in bucket names.

**Comment by vacri** [comment]
```s3://s3-ap-southeast-2.amazonaws.com/BUCKET.WITH.DOTS.IN```

The above used to work in 1.1.1 (my bucket is in ap-southeast-2), but no longer does in 1.2.1, as apt-transport-s3 can't figure out the bucket name from the above anymore. It uses an alternate way to address the s3 bucket.

It's extremely frustrating since a) this repo serves some clients over https, hence the 'domain name' bucket name format is basically required by AWS, and b) the repo is PGP-signed anyway (with a separately-installed key on the client), so https is not as critical.

With 1.2.1, I can't find a combination of factors to make it work with dotted names, trying various things in /etc/apt/s3auth.conf combined with the .list file.

**Comment by rene00** [comment]
Could https://github.com/BashtonLtd/apt-transport-s3/pull/37 please be considered and merged?

**Comment by Joshisland** [comment]
We had a similar problem, and here is a workaround.
Instead of

> deb s3://packages.example.com stable main

we reviewed the code, tried

> deb s3:///packages.example.com stable main

, and it worked.

**Comment by nzjrs** [comment]
Ha, confirming this comical error.

**Comment by vorlock** [comment]
Issue was related to path and vhost style bucket names, right now in (1.3.0) we switched fully to path based style so in theory this (dotted bucket naming convention and TLS cert) shouldn't be the issue anymore, so I'm closing this issue but if something is still not working feel free to repopen it.
